{% set name = "tldraw" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tldraw-{{ version }}.tar.gz
  sha256: 1267f0dcf14dd2dd70fe139306bb8ea1e448cdfdbcdded1fc1eec08b3766354e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.7
    - anywidget
    - ipylab
    - requests
    - ipykernel

test:
  imports:
    - tldraw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kolibril13/jupyter-tldraw
  summary: Tldraw whiteboard functionality for Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
