{% set name = "tldraw" %}
{% set version = "2.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tldraw-{{ version }}.tar.gz
  sha256: 834d4aa06b31407c531f25a837f46982fded819d76328b3bdc790d3e362742de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-jupyter-builder
    - pip
    - nodejs
  run:
    - python >=3.7
    - anywidget

test:
  imports:
    - tldraw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kolibril13/jupyter-tldraw
  summary: Tldraw whiteboard functionality for Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
