{% set name = "tldraw" %}
{% set version = "5.0.0" %}
{% set python_min = "3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tldraw-{{ version }}.tar.gz
  sha256: 3198ba6b02930373678573c2393f56f0907ce165adbf07690dc684d88670e88e

build:
  noarch: python
  script:
    - rm -rf node_modules
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - pip
    - nodejs
  run:
    - python >={{ python_min }}
    - anywidget
    - requests
    - ipylab
    - ipykernel

test:
  imports:
    - tldraw
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kolibril13/jupyter-tldraw
  summary: Tldraw whiteboard functionality for Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
