{% set name = "tldraw" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tldraw-{{ version }}.tar.gz
  sha256: 80b7f80fce79b5bc9e1f4260581d72ec69e8245b8eaace193259629f32189c78

build:
  noarch: python
  script:
    - rm -rf node_modules
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - pip
    - nodejs
  run:
    - python >={{ python_min }}
    - anywidget
    - requests
    - ipylab
    - ipykernel

test:
  imports:
    - tldraw
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kolibril13/jupyter-tldraw
  summary: Tldraw whiteboard functionality for Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
