{% set name = "tldraw" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tldraw-{{ version }}.tar.gz
  sha256: 34bdad911496e41a69fac585f56d3613c7f8d21a45268b805dc9fa48f64518a1

build:
  noarch: python
  script:
    - rm -rf node_modules
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-jupyter-builder
    - pip
    - nodejs
  run:
    - python >=3.7
    - anywidget
    - requests
    - ipylab
    - ipykernel

test:
  imports:
    - tldraw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kolibril13/jupyter-tldraw
  summary: Tldraw whiteboard functionality for Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
